### ISSUE TITLE
Add specs?

### ISSUE THREAD

**Issue by oleander** [judofyr/gash#7]
It looks like @trans is the new maintainer of Gash which I guess would mean a bunch of changes, one being specs.

So my question is; are you (@trans) about to add spec related code in the near feature? Just adding an empty directory and a test framework (preferable rspec or minitest) would be fine with me.
The idea was to do a fork, fix some bugs and do a pull request, but I don't like contributing to a project without adding my own specs.

**Comment by oleander** [comment]
@trans How about this?

**Comment by trans** [comment]
Hi--

Looks good.

Ultimately I prefer not using RSpec, but that's okay, feel free to use RSpec for the time being.

**Comment by oleander** [comment]
What would you like to use instead?
I'm just curious.

**Comment by trans** [comment]
Well, I was thinking about using Lemon. Lemon is a tightly coupled unit testing framework. Since we are not TDDing, Lemon can also generate a complete skeleton for the entire project, which would ease working through complete coverage.

However, I hadn't gotten past just thinking about this idea, and at the time I mostly expected that I be about the only person writing any tests `;)` Since that seems not be the case, and I know others are more familiar with RSpec, then I'm fine with RSpec. I am working on an Rspec clone that runs on top of Ruby Test. Ultimately I'd like to transition over to that, which should be a very simple transition. So it's really no bother. Just don't get too crazy with the mocks `:)`

**Comment by oleander** [comment]
Using Lemon sounds like a good idea. I'll take a look at it later this week.
I've added some specs using RSpec for now. Se pull request #9.

**Comment by trans** [comment]
Awesome. I'll see what I can get done tomorrow. After that I am going to be out of town for a few days. When I get back I'll work on generating the Lemon skeleton. This is really good b/c it gives me a nice opportunity to clean-up, and beef-up, the generator code which I've been wanting to do for a while.
